### PR TITLE
Update faye-websocket to at least 0.10.0

### PR DESCRIPTION
**Pull request by lazyfrosch**
Tested locally.

I hope they will also include SNI support with this PR soon:
https://github.com/faye/faye-websocket-node/pull/50

### CODE REVIEW

**Comment by engelgabriel** [comment]
+1

**Comment by pscanf** [comment]
Done in `2.0.0`

**Comment by engelgabriel** [comment]
But migrating to 2.0.0 is not a trivial work, this would benefit people before they can afford the time to migrate.

**Comment by pscanf** [comment]
That is unfortunately true. Would you suggest pushing out a `0.7.0` with the upgraded `faye-websocket` and PR #87 ?

**Comment by engelgabriel** [comment]
that would be awesome if you can do it. I started the migration to 2.0.0 already when I saw your branch... but it took me over 8 hours and it is not finished, so I can only imaged more people will have to deal with the same.

**Comment by pscanf** [comment]
Emmh, sorry :sweat_smile: . I'll try the `0.7.0` thing.

Unfortunately I've made a bit of a mess with it, leaving the library stale for too long, and then never getting around publishing `1.0.0`. The API cahnged, but hopefully for the best.

I'm writing a CHANGELOG to summarize changes. If you can help with some tips about upgrading that would be awesome.

**Comment by pscanf** [comment]
Merged changes in `v0.7.0`.

**Pull request closed without merging**
