### PR TITLE
Created the login function to allow custom login methods.

### PR DESCRIPTION
**Pull request by engelgabriel**
Needed for https://github.com/RocketChat/hubot-rocketchat/issues/58

### CODE REVIEW

**Comment by teon** [comment]
+1

**Comment by giray** [comment]
+1

**Comment by engelgabriel** [comment]
I dont understand why "The Travis CI build failed". Any hints?

**Comment by engelgabriel** [comment]
OK, can anyone help me with the test?

**Comment by pscanf** [comment]
`2.0.0` is out. It's not a smooth upgrade from `0.6.1`, but at least it should have the functionality requested.

**Comment by engelgabriel** [comment]
But migrating to 2.0.0 is not a trivial work, this would benefit people before they can afford the time to migrate.

**Comment by pscanf** [comment]
Merged changes in `v0.7.0`.

**Pull request closed without merging**
